### ISSUE TITLE
Create SoundDrop fails for private tracks

### ISSUE THREAD

**Issue by starkcoffee** [sounddrop/sounddrop#37] opened 2015-10-05 18:06 UTC
When creating a SoundDrop, if you choose a private track from the list of SoundCloud tracks, after you submit the form, you get an error page. It's probably happening because we can't retrieve private sounds with the api. We should filter out private tracks from the drop down list for now.

**Comment by berlintam** [comment] 2016-08-12 15:34
I'm closing this issue b/c I made a duplicate of it by accident. Nynne's claimed that issue & I've put a bunch of additional info in there already. 
https://github.com/sounddrop/sounddrop/issues/58

oops!

**Closed as completed by berlintam** 2016-08-12 15:34 UTC
Labels: bug
